name: Generate Bulletin Manifest

on:
  push:

jobs:
  generate-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Generate bulletin manifest
        run: node generate-bulletin-manifest.js
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generate bulletin manifest
          commit_options: '--no-verify --signoff'
          branch: ${{ github.ref }}
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
