name: Update Bulletin Links

on:
  push:
    branches:
      - main

jobs:
  update-bulletin-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Fetch Bulletin Links
        run: |
          latest_bulletins=$(ls -t bulletin/*.pdf | head -n 3 | xargs -I{} sh -c 'echo "$(basename "{}" .pdf)|{}"' | tac)
          echo "::set-env name=latest_bulletins::$latest_bulletins"
      
      - name: Update Bulletin Links
        run: |
          latest_bulletins=(${latest_bulletins// / })
          for ((i=0; i<${#latest_bulletins[@]}; i+=2)); do
            sed -i "s#<em>.*</a></em><br>#<em><a href=\"/${latest_bulletins[$i+1]}\" target=\"_blank\">${latest_bulletins[$i]}</a></em><br>#g" index.html
          done
      
      - name: Commit changes
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git commit -am "Update bulletin links"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
